services:
  - type: web
    name: youtube-transcript-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000  # Render auto-assigns a port
